<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'name' => 'Covergrip - Bullpadel',
                'short_name' => 'CUBREGRIP',
                'description' => 'For players of all levels who want to improve their grip grip. Ideal for players of all levels who want to improve their grip grip.',
                'price' => 5,
                'category' => 'Accesories',
                'brand' => 'Bullpadel',
                'url' => 'cubregrip-bullpadel',
            ],
            [
                'name' => 'Shoe deodorant',
                'short_name' => 'DESODORANTE',
                'description' => 'This deodorant effectively neutralizes the odors of sports shoes. You can take off your shoes safely. The BAMA neutralizing spray does not mask odors, removes them and leaves a fresh perfume. VERY easy to use.',
                'price' => 6,
                'category' => 'Accesories',
                'brand' => 'Bama',
                'url' => 'desodorante-bama-calzado',
            ],
            [
                'name' => 'Cap - Adidas',
                'short_name' => 'GORRA',
                'description' => 'Padel/Tennis players looking for a cap with good sun protection. This Adidas sports cap will protect you from the sun and bring you a lot of comfort thanks to its lightness.',
                'price' => 17,
                'category' => 'Accesories',
                'brand' => 'Adidas',
                'url' => 'gorra-adidas',
            ],
            [
                'name' => 'Liquid Magnesium',
                'short_name' => 'MAGNESIO',
                'description' => 'Our team has created this magnesium for climbers who sweat little in climbing but want a magnesium with a little grip without too much alcohol. With little percentage of alcohol (30%) to care for the skin of the hands, dry less hands after use. It can be used as a supplement to magnesium powder.',
                'price' => 7,
                'category' => 'Accesories',
                'brand' => 'Simond',
                'url' => 'magnesioliquido-simond',
            ],
            [
                'name' => 'Wristbands - Adidas',
                'short_name' => 'MUNEQUERAS',
                'description' => 'For playing racquet/shovel sports in hot weather, they are also suitable for other racquet/shovel sports. This long sports wristband Adidas offers maximum absorption of sweat. Stops squirting along the arm for easy racket/shovel grip.',
                'price' => 12,
                'category' => 'Accesories',
                'brand' => 'Adidas',
                'url' => 'munequeras-adidas',
            ],
            [
                'name' => 'Bandage suitable - Tarmaik',
                'short_name' => 'VENDA',
                'description' => 'Reusable bandage suitable for bandaging joints or muscles during sports practice. Elastic and reusable support bandage 8 cm x 1.2 m. Useful with self-adhesive bandages to hold and protect joints and muscles.',
                'price' => 6,
                'category' => 'Accesories',
                'brand' => 'Tarmaik',
                'url' => 'vendasujecion-tarmaik',
            ],
            [
                'name' => 'Padel balls - Babolat',
                'short_name' => 'PELOTASBAB',
                'description' => 'Paddle players in improvement. Paddle balls with pressure, durable and live for training.',
                'price' => 5,
                'category' => 'Balls',
                'brand' => 'Babolat',
                'url' => 'pelota-de-padel-babolat',
            ],
            [
                'name' => 'Padel balls - Head',
                'short_name' => 'PELOTASHEA',
                'description' => 'Ideal for players looking for a live ball for quick exchanges. The Head Pro ball, in its S version, has a completely new core, which gives it speed and dynamism.',
                'price' => 5,
                'category' => 'Balls',
                'brand' => 'Head',
                'url' => 'pelota-de-padel-head',
            ],
            [
                'name' => 'Ball pressurizer - Kuikma',
                'short_name' => 'PRESURIZADORKUI',
                'description' => 'It maintains the pressure of the paddle balls between the two parts to prolong its service life.',
                'price' => 20,
                'category' => 'Balls',
                'brand' => 'Kuikma',
                'url' => 'presurizador-padel-kuikma',
            ],
            [
                'name' => 'Ball pressurizer - Tuboplus',
                'short_name' => 'PRESURIZADORTUB',
                'description' => 'Ball pressurizer, keeps the pressure of the ball over time, preventing the ball from losing pot in use.',
                'price' => 20,
                'category' => 'Balls',
                'brand' => 'Tuboplus',
                'url' => 'presurizador-padel-tuboplus',
            ],
            [
                'name' => 'Balls Pack - Head',
                'short_name' => 'PACKHEA',
                'description' => 'Pack 3 pots Head Padel Professional, for experienced players, the official balls of the circuit WTP.',
                'price' => 21,
                'category' => 'Balls',
                'brand' => 'Head',
                'url' => 'tripack-pelota-padel-head',
            ],
            [
                'name' => 'Balls Pack - Kuikma',
                'short_name' => 'PACKKUI',
                'description' => 'Designed for expert players who want a ball that stays dynamic in slow playing conditions (moderate temperature, sea level, humidity) Ideal for expert paddle players who want to play with live ball in slow playing conditions (moderate temperature, sea level, humidity).',
                'price' => 13,
                'category' => 'Balls',
                'brand' => 'Kuikma',
                'url' => 'tripack-pelota-padel-kuikma',
            ],
            [
                'name' => 'Kid T-shirt - Artengo',
                'short_name' => 'CAMISETANINOART',
                'description' => 'Our designers have designed this t-shirt for young tennis players who play with warm weather, also suitable for other racquet sports. Lightweight and breathable tennis shirt.Its varied colors allow to combine it with the short 500 of your choice to show off a very trendy style.',
                'price' => 12,
                'category' => 'Clothes',
                'brand' => 'Artengo',
                'url' => 'camiseta-artengo-nino',
            ],
            [
                'name' => 'Man T-shirt - Black Crown',
                'short_name' => 'CAMISETAHOMBREBLA',
                'description' => 'Made of polyamide and elastane, innovative fibers that provide lightness, mobility and comfort. They are quick drying, absorb moisture and are well ventilated.',
                'price' => 32,
                'category' => 'Clothes',
                'brand' => 'Blackcrown',
                'url' => 'camiseta-blackcrown-hombre',
            ],
            [
                'name' => 'Woman T-shirt - Black Crown',
                'short_name' => 'CAMISETAMUJERBLA',
                'description' => 'It is breathable, absorbs moisture and dries quickly. They provide lightness, mobility and comfort. With two large pockets and elastic waist.',
                'price' => 46,
                'category' => 'Clothes',
                'brand' => 'Blackcrown',
                'url' => 'camiseta-blackcrown-mujer',
            ],
            [
                'name' => 'Man Short - Artengo',
                'short_name' => 'PANTALONHOMBREART',
                'description' => 'Our development teams have created these pants so you can get started in racquet sports without getting hot. Tennis shorts to feel comfortable on the court. Light and with good freedom of movement, comfortable to wear while playing. Large pockets to store balls without discomfort.',
                'price' => 6,
                'category' => 'Clothes',
                'brand' => 'Artengo',
                'url' => 'pantalon-artengo-hombre',
            ],
            [
                'name' => 'Woman Short - Artengo',
                'short_name' => 'PANTALONMUJERART',
                'description' => 'Our team, passionate about tennis, has designed this tennis shorts for matches or training. With this breathable short, you are ready for a series of exchanges or stitches! Special design pockets to keep the balls.',
                'price' => 12,
                'category' => 'Clothes',
                'brand' => 'Artengo',
                'url' => 'pantalon-artengo-mujer',
            ],
            [
                'name' => 'Girl dress - Artengo',
                'short_name' => 'VESTIDONINAART',
                'description' => 'Our designers have designed this dress for tennis practice, garment also suitable for other racquet sports. Dress great style for your future champion to win with class!',
                'price' => 20,
                'category' => 'Clothes',
                'brand' => 'Artengo',
                'url' => 'vestido-artengo-nina',
            ],
            [
                'name' => 'Kid padle bat - Artengo',
                'short_name' => 'PALANINOART',
                'description' => 'Ideal for junior padel players (9 to 11 years old) in initiation. Ideal for beginner level padel players looking for a shovel that combines manageability and control.',
                'price' => 25,
                'category' => 'Padelbat',
                'brand' => 'Artengo',
                'url' => 'pala-de-padel-artengo-nino',
            ],
            [
                'name' => 'Padle bat - Babolat',
                'short_name' => 'PALABAB',
                'description' => 'Designed for paddle tennis players in advanced training. Tear-shaped multi-purpose paddle, perfect if you are looking for power and control at the same time.',
                'price' => 85,
                'category' => 'Padelbat',
                'brand' => 'Babolat',
                'url' => 'pala-de-padel-babolat',
            ],
            [
                'name' => 'Padle bat - Babolat',
                'short_name' => 'PALABAB2',
                'description' => 'Designed for expert padel players. The Babolat Technical Viper is a paddle shovel for expert players looking for power and precision in attack strikes.',
                'price' => 290,
                'category' => 'Padelbat',
                'brand' => 'Babolat',
                'url' => 'pala-de-padel-babolat2',
            ],
            [
                'name' => 'Padle bat - Head',
                'short_name' => 'PALAHEA',
                'description' => 'Designed for paddle players in perfecting. Ideal for paddle players in perfecting looking for a powerful paddle paddle.',
                'price' => 90,
                'category' => 'Padelbat',
                'brand' => 'Head',
                'url' => 'pala-de-padel-head',
            ],
            [
                'name' => 'Padle bat - Head',
                'short_name' => 'PALAHEA2',
                'description' => 'Designed for expert padel players. Improve touch, precision and power with the ALPHA ELITE PADDLE, the most powerful paddle in a control-oriented range.',
                'price' => 160,
                'category' => 'Padelbat',
                'brand' => 'Head',
                'url' => 'pala-de-padel-head2',
            ],
            [
                'name' => 'Kid padle bat - Kuikma',
                'short_name' => 'PALANINOKUI',
                'description' => 'Thermal zone for 3 blades. Large central area. Bottom pocket for shoes. Pockets for personal items. Removable and adjustable ergonomic strap. Padded handles.',
                'price' => 45,
                'category' => 'Padelbat',
                'brand' => 'Kuikma',
                'url' => 'pala-padel-kuikma-nino',
            ],
            [
                'name' => 'Basic padle bat bag - Black Crown',
                'short_name' => 'PALETEROBLA',
                'description' => 'Thermal zone for 3 blades. Large central area. Bottom pocket for shoes. Pockets for personal items. Removable and adjustable ergonomic strap. Padded handles',
                'price' => 74,
                'category' => 'Padelbatbag',
                'brand' => 'Blackcrown',
                'url' => 'paletero-blackcrown',
            ],
            [
                'name' => 'Basic padle bat bag - Bullpadel',
                'short_name' => 'PALETEROBAB',
                'description' => 'Designed for paddle players in improvement. It is ideal for perfecting paddle players who want to transport their belongings and protect paddles.',
                'price' => 35,
                'category' => 'Padelbatbag',
                'brand' => 'Bullpad',
                'url' => 'paletero-bullpadel',
            ],
            [
                'name' => 'Padle bat bag - Bullpadel',
                'short_name' => 'PALETEROBUL',
                'description' => 'Designed for expert paddle players. Paddle backpack chosen by Juan Tello and Fede Chingotto (WPT players). It is ideal for expert paddle players who want to transport their belongings and protect paddles.',
                'price' => 50,
                'category' => 'Padelbatbag',
                'brand' => 'Bullpad',
                'url' => 'paletero-bullpadelbag',
            ],
            [
                'name' => 'NextGen Padle bat bag - Bullpadel',
                'short_name' => 'PALETERONEXBUL',
                'description' => 'Designed for expert padel players. Ideal pallet for expert paddle players who want to transport their belongings and protect paddles.',
                'price' => 73,
                'category' => 'Padelbatbag',
                'brand' => 'Bullpad',
                'url' => 'paletero-bullpadelnext',
            ],
            [
                'name' => 'Basic padle bat bag - Head',
                'short_name' => 'PALETEROHEA',
                'description' => 'Designed for beginner level paddle players. Small paddle paddle player ideal for beginner level paddle players.',
                'price' => 35,
                'category' => 'Padelbatbag',
                'brand' => 'Head',
                'url' => 'paletero-head',
            ],
            [
                'name' => 'Basic padle bat bag - Kuikma',
                'short_name' => 'PALETEROKUI',
                'description' => 'Expert paddle tennis players. Ideal backpack for expert paddle players looking for a bag to transport paddles and the whole set.',
                'price' => 35,
                'category' => 'Padelbatbag',
                'brand' => 'Kuikma',
                'url' => 'paletero-kuikma',
            ],
            [
                'name' => 'Woman sneakers - Artengo',
                'short_name' => 'DEPORMUJERART',
                'description' => 'The practice of paddle, expert level. These paddle tennis shoes will give you the necessary support and duration for intensive travel.',
                'price' => 40,
                'category' => 'Sportshoes',
                'brand' => 'Artengo',
                'url' => 'zapatillas-artengo-mujer',
            ],
            [
                'name' => 'Man sneakers - Babolat',
                'short_name' => 'DEPORHOMBREBAB',
                'description' => 'Designed to play paddle, expert level. Babolat Jet Premura shoes are designed to play paddle, expert level. Juan Lebron’s shoes, number one in the world.',
                'price' => 150,
                'category' => 'Sportshoes',
                'brand' => 'Babolat',
                'url' => 'zapatillas-babolat-hombre',
            ],
            [
                'name' => 'Man sneakers - Bpthermofit',
                'short_name' => 'DEPORHOMBREBPT',
                'description' => 'Designed for expert paddle players. Bpthermofit movea 22 shoes are a versatile model for paddle tennis competitors. They have reinforcements for a great durability and are comfortable thanks to the knitted mesh on the toe.',
                'price' => 115,
                'category' => 'Sportshoes',
                'brand' => 'Bpthermofit',
                'url' => 'zapatillas-bpthermofit-hombre',
            ],
            [
                'name' => 'Woman sneakers - Kuikma',
                'short_name' => 'DEPORMUJERKUI',
                'description' => 'Designed for expert level paddle practice. These paddle tennis shoes will give you the necessary dynamism in intensive travel thanks to their lightness and flexibility.',
                'price' => 65,
                'category' => 'Sportshoes',
                'brand' => 'Kuikma',
                'url' => 'zapatillas-kuikma-mujer',
            ],
            [
                'name' => 'Kid sneakers - Kuikma',
                'short_name' => 'DEPORNINOKUI',
                'description' => 'The practice of paddle, initiation level. The paddle tennis shoes will provide the necessary grip to young paddle players to play on synthetic grass with sand without slipping.',
                'price' => 19,
                'category' => 'Sportshoes',
                'brand' => 'Kuikma',
                'url' => 'zapatillas-kuikma-nino',
            ],
            [
                'name' => 'Kid sneakers - Kuikma',
                'short_name' => 'DEPORNINOKUI2',
                'description' => 'For the practice of paddle, advanced level. The paddle shoes will give you the necessary grip to play on synthetic grass with sand and cushioning for better absorption of impacts.',
                'price' => 28,
                'category' => 'Sportshoes',
                'brand' => 'Kuikma',
                'url' => 'zapatillas-kuikma-nino2',
            ],
        ];

        DB::table('products')->insert($products);
    }
}
