<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'name' => 'Cubregrip - Bullpadel',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Accesories',
                'brand' => 'Bullpadel',
                'url' => 'cubregrip-bullpadel',
            ],
            [
                'name' => 'Desodorante de calzado',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Accesories',
                'brand' => 'Bama',
                'url' => 'desodorante-bama-calzado',
            ],
            [
                'name' => 'Gorra - Adidas',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Accesories',
                'brand' => 'Adidas',
                'url' => 'gorra-adidas',
            ],
            [
                'name' => 'Magnesio líquido',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Accesories',
                'brand' => 'Simond',
                'url' => 'magnesioliquido-simond',
            ],
            [
                'name' => 'Munequeras - Adidas',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Accesories',
                'brand' => 'Adidas',
                'url' => 'munequeras-adidas',
            ],
            [
                'name' => 'Venda de sujecion - Tarmaik',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Accesories',
                'brand' => 'Tarmaik',
                'url' => 'vendasujecion-tarmaik',
            ],
            [
                'name' => 'Pelotas de padel - Babolat',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Balls',
                'brand' => 'Babolat',
                'url' => 'pelota-de-padel-babolat',
            ],
            [
                'name' => 'Pelotas de padel - Head',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Balls',
                'brand' => 'Head',
                'url' => 'pelota-de-padel-head',
            ],
            [
                'name' => 'Presurizador para pelotas - Kuikma',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Balls',
                'brand' => 'Kuikma',
                'url' => 'presurizador-padel-kuikma',
            ],
            [
                'name' => 'Presurizador para pelotas - Tuboplus',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Balls',
                'brand' => 'Tuboplus',
                'url' => 'presurizador-padel-tuboplus',
            ],
            [
                'name' => 'Pack de pelotas - Head',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Balls',
                'brand' => 'Head',
                'url' => 'tripack-pelota-padel-head',
            ],
            [
                'name' => 'Pack de pelotas - Kuikma',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Balls',
                'brand' => 'Kuikma',
                'url' => 'tripack-pelota-padel-kuikma',
            ],
            [
                'name' => 'Camiseta de nino - Artengo',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Clothes',
                'brand' => 'Artengo',
                'url' => 'camiseta-artengo-nino',
            ],
            [
                'name' => 'Camiseta de hombre - Black Crown',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Clothes',
                'brand' => 'Blackcrown',
                'url' => 'camiseta-blackcrown-hombre',
            ],
            [
                'name' => 'Camiseta de mujer - Black Crown',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Clothes',
                'brand' => 'Blackcrown',
                'url' => 'camiseta-blackcrown-mujer',
            ],
            [
                'name' => 'Pantalon de hombre - Artengo',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Clothes',
                'brand' => 'Artengo',
                'url' => 'pantalon-artengo-hombre',
            ],
            [
                'name' => 'Pantalon de mujer - Artengo',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Clothes',
                'brand' => 'Artengo',
                'url' => 'pantalon-artengo-mujer',
            ],
            [
                'name' => 'Vestido de nina - Artengo',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Clothes',
                'brand' => 'Artengo',
                'url' => 'vestido-artengo-nina',
            ],
            [
                'name' => 'Pala de padel de nino - Artengo',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbat',
                'brand' => 'Artengo',
                'url' => 'pala-de-padel-artengo-nino',
            ],
            [
                'name' => 'Pala de padel - Babolat',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbat',
                'brand' => 'Babolat',
                'url' => 'pala-de-padel-babolat',
            ],
            [
                'name' => 'Pala de padel - Babolat',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbat',
                'brand' => 'Babolat',
                'url' => 'pala-de-padel-babolat2',
            ],
            [
                'name' => 'Pala de padel - Head',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbat',
                'brand' => 'Head',
                'url' => 'pala-de-padel-head',
            ],
            [
                'name' => 'Pala de padel - Head',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbat',
                'brand' => 'Head',
                'url' => 'pala-de-padel-head2',
            ],
            [
                'name' => 'Pala de padel de nino - Kuikma',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbat',
                'brand' => 'Kuikma',
                'url' => 'pala-padel-kuikma-nino',
            ],
            [
                'name' => 'Paletero basico - Black Crown',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbatbag',
                'brand' => 'Blackcrown',
                'url' => 'paletero-blackcrown',
            ],
            [
                'name' => 'Paletero basico - Bullpadel',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbatbag',
                'brand' => 'Bullpad',
                'url' => 'paletero-bullpadel',
            ],
            [
                'name' => 'Paletero mochila - Bullpadel',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbatbag',
                'brand' => 'Bullpad',
                'url' => 'paletero-bullpadelbag',
            ],
            [
                'name' => 'Paletero nextGen - Bullpadel',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbatbag',
                'brand' => 'Bullpad',
                'url' => 'paletero-bullpadelnext',
            ],
            [
                'name' => 'Paletero basico - Head',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbatbag',
                'brand' => 'Head',
                'url' => 'paletero-head',
            ],
            [
                'name' => 'Paletero basico - Kuikma',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Padelbatbag',
                'brand' => 'Kuikma',
                'url' => 'paletero-kuikma',
            ],
            [
                'name' => 'Deportivas de mujer - Artengo',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Sportshoes',
                'brand' => 'Artengo',
                'url' => 'zapatillas-artengo-mujer',
            ],
            [
                'name' => 'Deportivas de hombre - Babolat',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Sportshoes',
                'brand' => 'Babolat',
                'url' => 'zapatillas-babolat-hombre',
            ],
            [
                'name' => 'Deportivas de hombre - Bpthermofit',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Sportshoes',
                'brand' => 'Bpthermofit',
                'url' => 'zapatillas-bpthermofit-hombre',
            ],
            [
                'name' => 'Deportivas de mujer - Kuikma',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Sportshoes',
                'brand' => 'Kuikma',
                'url' => 'zapatillas-kuikma-mujer',
            ],
            [
                'name' => 'Deportivas de nino - Kuikma',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Sportshoes',
                'brand' => 'Kuikma',
                'url' => 'zapatillas-kuikma-nino',
            ],
            [
                'name' => 'Deportivas de nino - Kuikma',
                'short_name' => '',
                'description' => '',
                'price' => 0,
                'category' => 'Sportshoes',
                'brand' => 'Kuikma',
                'url' => 'zapatillas-kuikma-nino',
            ],
        ];

        DB::table('products')->insert($products);
    }
}
